dados_produtos = [
    {'nome': 'Celular', 'preco': 1000.00},
    {'nome': 'Notebook', 'preco': 2000.00},
    {'nome': 'Camiseta', 'preco': 30.00},
    {'nome': 'Tênis', 'preco': 80.00},
    {'nome': 'Livro', 'preco': 25.00},
    {'nome': 'Fone de Ouvido', 'preco': 50.00},
    {'nome': 'Bicicleta', 'preco': 500.00},
    {'nome': 'Mochila', 'preco': 40.00},
    {'nome': 'Relógio', 'preco': 120.00},
    {'nome': 'Cadeira de Escritório', 'preco': 150.00},
    {'nome': 'Laptop', 'preco': 1500.00},
    {'nome': 'Sapato Social', 'preco': 70.00},
    {'nome': 'Câmera DSLR', 'preco': 800.00},
    {'nome': 'Camisa Polo', 'preco': 45.00},
    {'nome': 'Mouse sem Fio', 'preco': 20.00},
    {'nome': 'Sofá', 'preco': 600.00},
    {'nome': 'Tablet', 'preco': 300.00},
    {'nome': 'Calça Jeans', 'preco': 40.00},
    {'nome': 'Ventilador de Teto', 'preco': 80.00},
    {'nome': 'Mala de Viagem', 'preco': 60.00},
    {'nome': 'Smart TV', 'preco': 900.00},
    {'nome': 'Jaqueta de Couro', 'preco': 150.00},
    {'nome': 'Cafeteira', 'preco': 40.00},
    {'nome': 'Mesa de Jantar', 'preco': 300.00},
    {'nome': 'Impressora', 'preco': 70.00},
    {'nome': 'Blusa de Moletom', 'preco': 35.00},
    {'nome': 'Aspirador de Pó', 'preco': 60.00},
    {'nome': 'Escova de Dentes Elétrica', 'preco': 25.00},
    {'nome': 'Mesa de Centro', 'preco': 50.00},
    {'nome': 'Panela de Pressão', 'preco': 30.00},
    {'nome': 'Tênis de Corrida', 'preco': 120.00},
    {'nome': 'Liquidificador', 'preco': 35.00},
    {'nome': 'Shorts', 'preco': 20.00},
    {'nome': 'Fogão a Gás', 'preco': 250.00},
    {'nome': 'Mesa de Escritório', 'preco': 80.00},
    {'nome': 'Cadeira de Praia', 'preco': 15.00},
    {'nome': 'Copo Térmico', 'preco': 10.00},
    {'nome': 'Tênis de Basquete', 'preco': 90.00},
    {'nome': 'Micro-ondas', 'preco': 120.00},
    {'nome': 'Toalha de Banho', 'preco': 10.00},
    {'nome': 'Óculos de Sol', 'preco': 50.00},
    {'nome': 'Bola de Futebol', 'preco': 15.00},
    {'nome': 'Ferro de Passar', 'preco': 30.00},
    {'nome': 'Edredom', 'preco': 70.00},
    {'nome': 'Máquina de Lavar Roupa', 'preco': 350.00},
    {'nome': 'Chapéu', 'preco': 25.00},
    {'nome': 'Bicicleta Ergométrica', 'preco': 400.00},
    {'nome': 'Cadeira de Balanço', 'preco': 90.00},
    {'nome': 'Chaleira Elétrica', 'preco': 25.00},
    {'nome': 'Cobertor', 'preco': 40.00},
    {'nome': 'Secador de Cabelo', 'preco': 20.00},
    {'nome': 'Abajur', 'preco': 15.00},
    {'nome': 'Escova de Cabelo', 'preco': 10.00},
    {'nome': 'Tapete', 'preco': 30.00},
    {'nome': 'Frigobar', 'preco': 150.00},
    {'nome': 'Espelho de Parede', 'preco': 40.00},
    {'nome': 'Fone de Ouvido Bluetooth', 'preco': 60.00},
    {'nome': 'Guarda-chuva', 'preco': 15.00},
    {'nome': 'Frigideira Antiaderente', 'preco': 25.00},
    {'nome': 'Caneta Esferográfica', 'preco': 2.00}
]
