produtos_categorias_data = [
    {'produto': 'Celular', 'categoria': 'Eletrônicos'},
    {'produto': 'Notebook', 'categoria': 'Eletrônicos'},
    {'produto': 'Camiseta', 'categoria': 'Roupas'},
    {'produto': 'Tênis', 'categoria': 'Calçados'},
    {'produto': 'Livro', 'categoria': 'Livros e Papelaria'},
    {'produto': 'Fone de Ouvido', 'categoria': 'Eletrônicos'},
    {'produto': 'Bicicleta', 'categoria': 'Esportes e Lazer'},
    {'produto': 'Mochila', 'categoria': 'Acessórios'},
    {'produto': 'Relógio', 'categoria': 'Acessórios'},
    {'produto': 'Cadeira de Escritório', 'categoria': 'Móveis'},
    {'produto': 'Laptop', 'categoria': 'Eletrônicos'},
    {'produto': 'Sapato Social', 'categoria': 'Calçados'},
    {'produto': 'Câmera DSLR', 'categoria': 'Eletrônicos'},
    {'produto': 'Camisa Polo', 'categoria': 'Roupas'},
    {'produto': 'Mouse sem Fio', 'categoria': 'Periféricos de Computador'},
    {'produto': 'Sofá', 'categoria': 'Móveis'},
    {'produto': 'Tablet', 'categoria': 'Eletrônicos'},
    {'produto': 'Calça Jeans', 'categoria': 'Roupas'},
    {'produto': 'Ventilador de Teto', 'categoria': 'Eletrodomésticos'},
    {'produto': 'Mala de Viagem', 'categoria': 'Esportes e Lazer'},
    {'produto': 'Smart TV', 'categoria': 'Eletrônicos'},
    {'produto': 'Jaqueta de Couro', 'categoria': 'Roupas'},
    {'produto': 'Cafeteira', 'categoria': 'Eletrodomésticos'},
    {'produto': 'Mesa de Jantar', 'categoria': 'Móveis'},
    {'produto': 'Impressora', 'categoria': 'Eletrodomésticos'},
    {'produto': 'Blusa de Moletom', 'categoria': 'Roupas'},
    {'produto': 'Aspirador de Pó', 'categoria': 'Eletrodomésticos'},
    {'produto': 'Escova de Dentes Elétrica', 'categoria': 'Acessórios'},
    {'produto': 'Mesa de Centro', 'categoria': 'Móveis'},
    {'produto': 'Panela de Pressão', 'categoria': 'Eletrodomésticos'},
    {'produto': 'Tênis de Corrida', 'categoria': 'Calçados'},
    {'produto': 'Liquidificador', 'categoria': 'Eletrodomésticos'},
    {'produto': 'Shorts', 'categoria': 'Roupas'},
    {'produto': 'Fogão a Gás', 'categoria': 'Eletrodomésticos'},
    {'produto': 'Mesa de Escritório', 'categoria': 'Móveis'},
    {'produto': 'Cadeira de Praia', 'categoria': 'Esportes e Lazer'},
    {'produto': 'Copo Térmico', 'categoria': 'Acessórios'},
    {'produto': 'Tênis de Basquete', 'categoria': 'Esportes e Lazer'},
    {'produto': 'Micro-ondas', 'categoria': 'Eletrodomésticos'},
    {'produto': 'Toalha de Banho', 'categoria': 'Acessórios'},
    {'produto': 'Óculos de Sol', 'categoria': 'Acessórios'},
    {'produto': 'Bola de Futebol', 'categoria': 'Esportes e Lazer'},
    {'produto': 'Ferro de Passar', 'categoria': 'Eletrodomésticos'},
    {'produto': 'Edredom', 'categoria': 'Acessórios'},
    {'produto': 'Máquina de Lavar Roupa', 'categoria': 'Eletrodomésticos'},
    {'produto': 'Chapéu', 'categoria': 'Acessórios'},
    {'produto': 'Bicicleta Ergométrica', 'categoria': 'Esportes e Lazer'},
    {'produto': 'Cadeira de Balanço', 'categoria': 'Móveis'},
    {'produto': 'Chaleira Elétrica', 'categoria': 'Eletrodomésticos'},
    {'produto': 'Cobertor', 'categoria': 'Acessórios'},
    {'produto': 'Secador de Cabelo', 'categoria': 'Eletrodomésticos'},
    {'produto': 'Abajur', 'categoria': 'Acessórios'},
    {'produto': 'Escova de Cabelo', 'categoria': 'Acessórios'},
    {'produto': 'Tapete', 'categoria': 'Acessórios'},
    {'produto': 'Frigobar', 'categoria': 'Eletrodomésticos'},
    {'produto': 'Espelho de Parede', 'categoria': 'Acessórios'},
    {'produto': 'Fone de Ouvido Bluetooth', 'categoria': 'Acessórios'},
    {'produto': 'Guarda-chuva', 'categoria': 'Acessórios'},
    {'produto': 'Frigideira Antiaderente', 'categoria': 'Eletrodomésticos'},
    {'produto': 'Caneta Esferográfica', 'categoria': 'Livros e Papelaria'},
]
